// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiForLabs.DataBase;

#nullable disable

namespace WebApiForLabs.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20250310141547_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiForLabs.DataBase.Models.Table1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Table1");
                });

            modelBuilder.Entity("WebApiForLabs.DataBase.Models.Table2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Table1Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Table1Id");

                    b.ToTable("Table2");
                });

            modelBuilder.Entity("WebApiForLabs.DataBase.Models.Table2", b =>
                {
                    b.HasOne("WebApiForLabs.DataBase.Models.Table1", "Table1")
                        .WithMany()
                        .HasForeignKey("Table1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table1");
                });
#pragma warning restore 612, 618
        }
    }
}
